import { catalog, type CatalogEntry, FAMILIES } from './manifest.js';

/**
 * The conventions-catalogue generator — renders the mechanized rule catalogue
 * FROM `manifest.ts` (the source of truth) into two committed projections:
 *
 * - the full four-channel catalogue inside `docs/13-linting.md`, spliced between
 *   GENERATED markers ({@link spliceCatalog}) — grouped by convention family;
 * - `skills/jterrazz-test/references/rules.md` — the agent-facing rule reference
 *   ({@link renderRules}).
 *
 * Output is deterministic (the manifest is pre-sorted), so `plugin.test.ts` can
 * assert freshness: running the generator must reproduce the committed files
 * byte-for-byte. `catalog-cli.ts` (bundled as `dist/catalog.js`) writes them;
 * `npm run docs` chains it alongside `typescript docs`, which regenerates the
 * `docs/reference/` projection.
 */

/** Markers delimiting the generated catalogue inside `docs/13-linting.md`. */
export const DOCS_START =
    '<!-- GENERATED:catalog — do not edit by hand; run `npm run docs`. Source: src/lint/manifest.ts -->';
export const DOCS_END = '<!-- /GENERATED:catalog -->';

/** First-line header stamped on the generated skill reference `rules.md`. */
export const RULES_HEADER = "<!-- GENERATED by 'npm run docs' — DO NOT EDIT -->";

/** Escape a markdown table cell (pipes would split the row). */
function cell(text: string): string {
    return text.replaceAll('|', String.raw`\|`);
}

/**
 * Render a GitHub-flavoured markdown table the way oxfmt (prettier) canonicalizes
 * one: each column padded to its widest cell (min 3). Emitting this form keeps the
 * generated files format-clean, so the freshness meta-test and the formatter agree.
 * All cell characters are BMP width-1 (Latin, arrows, curly quotes), so
 * `String.length` equals the display width.
 */
function table(headers: string[], rows: string[][]): string[] {
    const widths = headers.map((header, index) =>
        Math.max(header.length, 3, ...rows.map((row) => row[index].length)),
    );
    const line = (cells: string[]): string =>
        `| ${cells.map((text, index) => text.padEnd(widths[index])).join(' | ')} |`;
    const separator = `| ${widths.map((width) => '-'.repeat(width)).join(' | ')} |`;
    return [line(headers), separator, ...rows.map(line)];
}

const CHANNEL_ORDER: Record<CatalogEntry['channel'], number> = {
    statique: 0,
    checker: 1,
    runtime: 2,
    process: 3,
};

/** The catalogue families, deterministically ordered. */
function families(): string[] {
    return [...new Set(catalog.map((entry) => entry.family))].sort((a, b) => a.localeCompare(b));
}

/** Per-channel row counts, for the generated intro line. */
function counts(): Record<CatalogEntry['channel'], number> {
    return {
        checker: catalog.filter((entry) => entry.channel === 'checker').length,
        process: catalog.filter((entry) => entry.channel === 'process').length,
        runtime: catalog.filter((entry) => entry.channel === 'runtime').length,
        statique: catalog.filter((entry) => entry.channel === 'statique').length,
    };
}

/**
 * One `## <family> — <title>` section per family, each a full five-column table
 * (Code · Implementation · Channel · Convention · Rationale) sorted by channel
 * then id/name. Shared by the docs catalogue.
 */
function catalogueSections(): string[] {
    return families().map((family) => {
        const rows = catalog
            .filter((entry) => entry.family === family)
            .sort((a, b) => CHANNEL_ORDER[a.channel] - CHANNEL_ORDER[b.channel])
            .map((entry) => [
                entry.id,
                `\`${entry.name}\``,
                entry.channel,
                cell(entry.convention),
                cell(entry.rationale),
            ]);
        return [
            `## ${family} — ${FAMILIES[family] ?? family}`,
            '',
            ...table(['Code', 'Implementation', 'Channel', 'Convention', 'Rationale'], rows),
        ].join('\n');
    });
}

/**
 * The full four-channel catalogue spliced into `docs/13-linting.md` between the
 * GENERATED markers — a counts line, then every family section. The surrounding
 * chapter prose is hand-maintained; only this region is generated.
 */
function renderDocsCatalog(): string {
    const c = counts();
    const intro = `Every rule the framework enforces, across its four channels — **statique** (${c.statique} oxlint rules), **checker** (${c.checker} bundled passes), **runtime** (${c.runtime} execution-time refusals), **process** (${c.process} review-borne rules) — sourced from one manifest so the code and the catalogue can never drift.`;
    const inner = [intro, ...catalogueSections()].join('\n\n');
    return `${DOCS_START}\n\n${inner}\n\n${DOCS_END}`;
}

/** Replace the region between the GENERATED markers of `docs/10` with a fresh catalogue. */
export function spliceCatalog(existing: string): string {
    const start = existing.indexOf(DOCS_START);
    const end = existing.indexOf(DOCS_END);
    if (start === -1 || end === -1) {
        throw new Error(
            `docs/13-linting.md is missing the GENERATED:catalog markers (${DOCS_START} … ${DOCS_END})`,
        );
    }
    return existing.slice(0, start) + renderDocsCatalog() + existing.slice(end + DOCS_END.length);
}

/**
 * The agent-facing rule reference `skills/jterrazz-test/references/rules.md` —
 * the same four-channel catalogue as `docs/10`, trimmed to what an agent needs
 * to apply and cite a rule (Code · Implementation · Channel · Enforces), grouped
 * by family. Stamped `DO NOT EDIT`; the skill routes here for rule ids.
 */
export function renderRules(): string {
    const sections = families().map((family) => {
        const rows = catalog
            .filter((entry) => entry.family === family)
            .sort((a, b) => CHANNEL_ORDER[a.channel] - CHANNEL_ORDER[b.channel])
            .map((entry) => [entry.id, `\`${entry.name}\``, entry.channel, cell(entry.convention)]);
        return [
            `## ${family} — ${FAMILIES[family] ?? family}`,
            '',
            ...table(['Code', 'Implementation', 'Channel', 'Enforces'], rows),
        ].join('\n');
    });

    const parts = [
        RULES_HEADER,
        '# `@jterrazz/test` — rule reference',
        '> Generated from `src/lint/manifest.ts` by `npm run docs` — every mechanized convention across the four enforcement channels (statique · checker · runtime · process). Rule ids are stable: cite them in suppressions and reviews. Narrative lives in `docs/12-conventions.md` (the constitution) and `docs/13-linting.md` (the static plugin + checker).',
        ...sections,
    ];
    return `${parts.join('\n\n')}\n`;
}
